from decimal import Decimal
import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0003_activity_owner_profile"),
        ("commerce", "0003_financial_quote_snapshot"),
        ("organizations", "0004_profilefollow"),
        ("payments", "0009_financial_allocation_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundFlowConfiguration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("platform_default", models.BooleanField(default=False)),
                ("strategy", models.CharField(choices=[("platform_collect", "Collecte Makolo"), ("provider_split", "Split provider"), ("direct_to_payee", "Direct bénéficiaire"), ("external", "Hors rails Makolo")], max_length=32)),
                ("configured_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("activity", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="fund_flow_configuration", to="activities.activity")),
                ("configured_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="configured_fund_flows", to=settings.AUTH_USER_MODEL)),
                ("offer", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="fund_flow_configuration", to="commerce.offer")),
                ("space", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="fund_flow_configuration", to="organizations.organization")),
            ],
        ),
        migrations.CreateModel(
            name="FinancialDestination",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("destination_type", models.CharField(choices=[("bank_account", "Compte bancaire"), ("mobile_money", "Mobile money"), ("connected_account", "Compte provider connecté"), ("merchant_account", "Compte marchand"), ("other", "Autre")], max_length=32)),
                ("provider", models.CharField(blank=True, max_length=60)),
                ("external_reference", models.CharField(blank=True, max_length=220)),
                ("display_name", models.CharField(max_length=160)),
                ("masked_label", models.CharField(blank=True, max_length=160)),
                ("last_digits", models.CharField(blank=True, max_length=8)),
                ("status", models.CharField(choices=[("pending", "En attente"), ("active", "Active"), ("disabled", "Désactivée")], default="pending", max_length=16)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_financial_destinations", to=settings.AUTH_USER_MODEL)),
                ("disabled_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="disabled_financial_destinations", to=settings.AUTH_USER_MODEL)),
                ("payee_profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="financial_destinations", to=settings.AUTH_USER_MODEL)),
                ("payee_space", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="financial_destinations", to="organizations.organization")),
            ],
        ),
        migrations.CreateModel(
            name="FundFlowRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("strategy", models.CharField(choices=[("platform_collect", "Collecte Makolo"), ("provider_split", "Split provider"), ("direct_to_payee", "Direct bénéficiaire"), ("external", "Hors rails Makolo")], max_length=32)),
                ("source_level", models.CharField(choices=[("platform", "Défaut Makolo"), ("space", "Espace"), ("activity", "Activity"), ("offer", "Offer")], max_length=16)),
                ("source_object_id", models.CharField(blank=True, max_length=64)),
                ("platform_custody", models.BooleanField(default=False)),
                ("platform_receivable_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("source_key", models.CharField(max_length=220, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("obligation", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="fund_flow_record", to="payments.paymentobligation")),
            ],
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference", models.CharField(editable=False, max_length=28, unique=True)),
                ("currency", models.CharField(max_length=3)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("status", models.CharField(choices=[("draft", "Brouillon"), ("ready", "Prêt"), ("processing", "En traitement"), ("settled", "Réglé"), ("cancelled", "Annulé"), ("failed", "Échoué")], default="draft", max_length=16)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_settlements", to=settings.AUTH_USER_MODEL)),
                ("payee_profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="settlements", to=settings.AUTH_USER_MODEL)),
                ("payee_space", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="settlements", to="organizations.organization")),
            ],
        ),
        migrations.CreateModel(
            name="SettlementItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("allocation_line", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="settlement_items", to="payments.financialallocationline")),
                ("ledger_entry", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="settlement_item", to="payments.ledgerentry")),
                ("settlement", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="payments.settlement")),
            ],
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference", models.CharField(editable=False, max_length=28, unique=True)),
                ("attempt", models.PositiveIntegerField()),
                ("provider", models.CharField(choices=[("sandbox", "Sandbox"), ("manual", "Manuel")], max_length=20)),
                ("status", models.CharField(choices=[("pending", "En attente"), ("processing", "En traitement"), ("succeeded", "Réussi"), ("failed", "Échoué"), ("cancelled", "Annulé"), ("reversed", "Reversé")], default="pending", max_length=16)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("idempotency_key", models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ("provider_reference", models.CharField(blank=True, max_length=220)),
                ("source_key", models.CharField(max_length=220, unique=True)),
                ("provider_fee", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("provider_settled_at", models.DateTimeField(blank=True, null=True)),
                ("failure_code", models.CharField(blank=True, max_length=120)),
                ("failure_message", models.CharField(blank=True, max_length=500)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("succeeded_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_payouts", to=settings.AUTH_USER_MODEL)),
                ("destination", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payouts", to="payments.financialdestination")),
                ("settlement", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payouts", to="payments.settlement")),
            ],
        ),
        migrations.CreateModel(
            name="FundMovement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("movement_type", models.CharField(choices=[("payout", "Payout"), ("payout_reversal", "Reversal payout"), ("direct_payee", "Paiement direct bénéficiaire"), ("provider_split_payee", "Split provider bénéficiaire"), ("provider_split_platform", "Split provider Makolo"), ("external_payee", "Paiement externe bénéficiaire")], max_length=32)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("provider", models.CharField(blank=True, max_length=60)),
                ("provider_reference", models.CharField(blank=True, max_length=220)),
                ("source_key", models.CharField(max_length=220, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("obligation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="fund_movements", to="payments.paymentobligation")),
                ("payout", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="fund_movements", to="payments.payout")),
            ],
        ),
        migrations.AddConstraint(
            model_name="fundflowconfiguration",
            constraint=models.CheckConstraint(condition=(models.Q(("activity__isnull", True), ("offer__isnull", True), ("platform_default", True), ("space__isnull", True)) | models.Q(("activity__isnull", True), ("offer__isnull", True), ("platform_default", False), ("space__isnull", False)) | models.Q(("activity__isnull", False), ("offer__isnull", True), ("platform_default", False), ("space__isnull", True)) | models.Q(("activity__isnull", True), ("offer__isnull", False), ("platform_default", False), ("space__isnull", True))), name="fundflow_exactly_one_scope"),
        ),
        migrations.AddConstraint(
            model_name="fundflowconfiguration",
            constraint=models.UniqueConstraint(condition=models.Q(("platform_default", True)), fields=("platform_default",), name="fundflow_single_platform_default"),
        ),
        migrations.AddConstraint(
            model_name="financialdestination",
            constraint=models.CheckConstraint(condition=(models.Q(("payee_profile__isnull", True), ("payee_space__isnull", False)) | models.Q(("payee_profile__isnull", False), ("payee_space__isnull", True))), name="findest_exactly_one_owner"),
        ),
        migrations.AddIndex(model_name="financialdestination", index=models.Index(fields=["status", "destination_type"], name="findest_status_type_idx")),
        migrations.AddConstraint(model_name="fundflowrecord", constraint=models.CheckConstraint(condition=models.Q(("platform_receivable_amount__gte", 0)), name="fundflow_receivable_nonnegative")),
        migrations.AddConstraint(model_name="settlement", constraint=models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="settlement_amount_positive")),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(condition=(models.Q(("payee_profile__isnull", True), ("payee_space__isnull", False)) | models.Q(("payee_profile__isnull", False), ("payee_space__isnull", True))), name="settlement_exactly_one_payee"),
        ),
        migrations.AddIndex(model_name="settlement", index=models.Index(fields=["status", "currency", "created_at"], name="settlement_status_curr_idx")),
        migrations.AddConstraint(model_name="settlementitem", constraint=models.CheckConstraint(condition=models.Q(("amount", 0), _negated=True), name="settlement_item_nonzero")),
        migrations.AddIndex(model_name="settlementitem", index=models.Index(fields=["settlement", "created_at"], name="settlement_item_set_idx")),
        migrations.AddConstraint(model_name="payout", constraint=models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="payout_amount_positive")),
        migrations.AddConstraint(model_name="payout", constraint=models.UniqueConstraint(fields=("settlement", "attempt"), name="payout_settlement_attempt_unique")),
        migrations.AddConstraint(model_name="payout", constraint=models.UniqueConstraint(condition=models.Q(("provider_reference", ""), _negated=True), fields=("provider", "provider_reference"), name="payout_provider_ref_unique")),
        migrations.AddIndex(model_name="payout", index=models.Index(fields=["status", "provider", "created_at"], name="payout_status_provider_idx")),
        migrations.AddConstraint(model_name="fundmovement", constraint=models.CheckConstraint(condition=models.Q(("amount", 0), _negated=True), name="fundmovement_amount_nonzero")),
        migrations.AddIndex(model_name="fundmovement", index=models.Index(fields=["movement_type", "occurred_at"], name="fundmovement_type_time_idx")),
    ]
