import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_audiences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0004_profilefollow"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationPoint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("information", "Information"), ("question", "Question"), ("confirmation", "Confirmation"), ("poll", "Sondage"), ("request", "Demande"), ("form_request", "Formulaire"), ("exchange", "Échange")], max_length=24)),
                ("response_mode", models.CharField(choices=[("none", "Aucune réponse"), ("free_text", "Texte libre"), ("boolean", "Oui / non"), ("single_choice", "Choix unique"), ("multiple_choice", "Choix multiples"), ("number", "Nombre"), ("date", "Date"), ("datetime", "Date et heure"), ("file", "Fichier"), ("voice", "Vocal")], default="none", max_length=24)),
                ("resolution_policy", models.CharField(choices=[("manual", "Manuelle"), ("plurality", "Pluralité"), ("absolute_majority", "Majorité absolue"), ("unanimity", "Unanimité"), ("threshold", "Seuil"), ("first_valid", "Première réponse valide"), ("no_outcome", "Sans résultat")], default="manual", max_length=24)),
                ("title", models.CharField(blank=True, max_length=220)),
                ("body", models.TextField(blank=True)),
                ("importance", models.CharField(choices=[("normal", "Normale"), ("important", "Importante"), ("critical", "Critique")], default="normal", max_length=16)),
                ("lifecycle", models.CharField(choices=[("draft", "Brouillon"), ("open", "Ouvert"), ("response_closed", "Réponses closes"), ("resolved", "Résolu"), ("expired", "Expiré"), ("cancelled", "Annulé"), ("superseded", "Remplacé")], default="draft", max_length=24)),
                ("response_visibility", models.CharField(choices=[("authorities_only", "Autorités uniquement"), ("respondent_and_authorities", "Répondant et autorités"), ("aggregate", "Résultats agrégés"), ("point_viewers", "Personnes pouvant voir le Point")], default="respondent_and_authorities", max_length=32)),
                ("requires_acknowledgement", models.BooleanField(default=False)),
                ("opens_at", models.DateTimeField(blank=True, null=True)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("allow_response_change", models.BooleanField(default=False)),
                ("threshold_value", models.PositiveIntegerField(blank=True, null=True)),
                ("shared_pinned_at", models.DateTimeField(blank=True, null=True)),
                ("client_reference", models.CharField(blank=True, max_length=80, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("response_closed_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="points", to="conversations.conversation")),
                ("expected_action_audience", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="expected_action_points", to="conversations.conversationaudienceset")),
                ("published_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="published_conversation_points", to=settings.AUTH_USER_MODEL)),
                ("represented_space", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="published_conversation_points", to="organizations.organization")),
                ("resolution_audience", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="resolution_points", to="conversations.conversationaudienceset")),
                ("response_audience", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="response_points", to="conversations.conversationaudienceset")),
                ("shared_pinned_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="shared_pinned_conversation_points", to=settings.AUTH_USER_MODEL)),
                ("supersedes", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="superseded_by_points", to="conversations.conversationpoint")),
                ("visibility_audience", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="visible_points", to="conversations.conversationaudienceset")),
            ],
            options={"ordering": ["-published_at", "-created_at", "id"]},
        ),
        migrations.CreateModel(
            name="ConversationPointOption",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=220)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("point", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="options", to="conversations.conversationpoint")),
            ],
            options={"ordering": ["position", "id"]},
        ),
        migrations.CreateModel(
            name="ConversationPointResponse",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("value", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("superseded", "Remplacée"), ("withdrawn", "Retirée")], default="active", max_length=16)),
                ("client_reference", models.CharField(blank=True, max_length=80, null=True)),
                ("submitted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="conversation_point_responses", to=settings.AUTH_USER_MODEL)),
                ("point", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="responses", to="conversations.conversationpoint")),
                ("represented_space", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="conversation_point_responses", to="organizations.organization")),
                ("supersedes", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="superseded_by_responses", to="conversations.conversationpointresponse")),
            ],
            options={"ordering": ["point_id", "submitted_at", "id"]},
        ),
        migrations.CreateModel(
            name="ConversationPointResolution",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("method", models.CharField(choices=[("manual", "Manuelle"), ("automatic", "Automatique"), ("domain_event", "Événement métier")], max_length=16)),
                ("summary", models.CharField(max_length=500)),
                ("resolved_at", models.DateTimeField()),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("point", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="resolution", to="conversations.conversationpoint")),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="resolved_conversation_points", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ConversationPointResolutionOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("option", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="resolution_links", to="conversations.conversationpointoption")),
                ("resolution", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="selected_option_links", to="conversations.conversationpointresolution")),
            ],
        ),
        migrations.CreateModel(
            name="ConversationPointUserState",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("pinned_at", models.DateTimeField(blank=True, null=True)),
                ("revisit_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("point", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_states", to="conversations.conversationpoint")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="conversation_point_user_states", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="PointExchangeEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("body", models.TextField(blank=True)),
                ("moderation_state", models.CharField(choices=[("visible", "Visible"), ("hidden", "Masquée"), ("removed", "Retirée")], default="visible", max_length=16)),
                ("client_reference", models.CharField(blank=True, max_length=80, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="conversation_exchange_entries", to=settings.AUTH_USER_MODEL)),
                ("point", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="exchange_entries", to="conversations.conversationpoint")),
                ("removed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="removed_conversation_exchange_entries", to=settings.AUTH_USER_MODEL)),
                ("reply_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="replies", to="conversations.pointexchangeentry")),
                ("represented_space", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="conversation_exchange_entries", to="organizations.organization")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AddConstraint(model_name="conversationpoint", constraint=models.UniqueConstraint(condition=models.Q(("client_reference__isnull", False)), fields=("client_reference",), name="conv_point_client_ref_unique")),
        migrations.AddConstraint(model_name="conversationpoint", constraint=models.CheckConstraint(condition=models.Q(("deadline_at__isnull", True)) | models.Q(("opens_at__isnull", True)) | models.Q(("deadline_at__gt", models.F("opens_at"))), name="conv_point_deadline_after_open")),
        migrations.AddConstraint(model_name="conversationpoint", constraint=models.CheckConstraint(condition=models.Q(("valid_until__isnull", True)) | models.Q(("opens_at__isnull", True)) | models.Q(("valid_until__gt", models.F("opens_at"))), name="conv_point_valid_after_open")),
        migrations.AddIndex(model_name="conversationpoint", index=models.Index(fields=["conversation", "lifecycle", "published_at"], name="conv_point_state_pub_idx")),
        migrations.AddIndex(model_name="conversationpoint", index=models.Index(fields=["deadline_at", "lifecycle"], name="conv_point_deadline_idx")),
        migrations.AddIndex(model_name="conversationpoint", index=models.Index(fields=["importance", "lifecycle"], name="conv_point_importance_idx")),
        migrations.AddConstraint(model_name="conversationpointoption", constraint=models.UniqueConstraint(fields=("point", "position"), name="conv_point_option_position_unique")),
        migrations.AddConstraint(model_name="conversationpointoption", constraint=models.UniqueConstraint(fields=("point", "label"), name="conv_point_option_label_unique")),
        migrations.AddConstraint(model_name="conversationpointresponse", constraint=models.UniqueConstraint(condition=models.Q(status="active", represented_space__isnull=True), fields=("point", "actor"), name="conv_resp_actor_active_unique")),
        migrations.AddConstraint(model_name="conversationpointresponse", constraint=models.UniqueConstraint(condition=models.Q(status="active", represented_space__isnull=False), fields=("point", "represented_space"), name="conv_resp_space_active_unique")),
        migrations.AddConstraint(model_name="conversationpointresponse", constraint=models.UniqueConstraint(condition=models.Q(("client_reference__isnull", False)), fields=("client_reference",), name="conv_resp_client_ref_unique")),
        migrations.AddIndex(model_name="conversationpointresponse", index=models.Index(fields=["point", "status"], name="conv_resp_point_status_idx")),
        migrations.AddIndex(model_name="conversationpointresponse", index=models.Index(fields=["actor", "status"], name="conv_resp_actor_status_idx")),
        migrations.AddIndex(model_name="conversationpointresponse", index=models.Index(fields=["represented_space", "status"], name="conv_resp_space_status_idx")),
        migrations.AddConstraint(model_name="conversationpointresolutionoption", constraint=models.UniqueConstraint(fields=("resolution", "option"), name="conv_resolution_option_unique")),
        migrations.AddConstraint(model_name="conversationpointuserstate", constraint=models.UniqueConstraint(fields=("point", "profile"), name="conv_point_user_state_unique")),
        migrations.AddIndex(model_name="conversationpointuserstate", index=models.Index(fields=["profile", "acknowledged_at"], name="conv_point_user_ack_idx")),
        migrations.AddIndex(model_name="conversationpointuserstate", index=models.Index(fields=["profile", "revisit_at"], name="conv_point_user_revisit_idx")),
        migrations.AddConstraint(model_name="pointexchangeentry", constraint=models.UniqueConstraint(condition=models.Q(("client_reference__isnull", False)), fields=("client_reference",), name="conv_exchange_client_ref_unique")),
        migrations.AddIndex(model_name="pointexchangeentry", index=models.Index(fields=["point", "created_at"], name="conv_exchange_point_idx")),
    ]
