import uuid
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_organizationfollow"),
        ("promotions", "0001_initial"),
        ("tickets", "0003_ticketwaitlistentry_tickettransfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(default="Programme fidélité", max_length=160)),
                ("description", models.TextField(blank=True)),
                ("points_name", models.CharField(default="points", max_length=40)),
                ("points_per_order", models.PositiveIntegerField(default=10)),
                ("points_per_ticket", models.PositiveIntegerField(default=5)),
                ("points_per_checkin", models.PositiveIntegerField(default=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_loyalty_programs", to=settings.AUTH_USER_MODEL)),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="loyalty_program", to="organizations.organization")),
            ],
        ),
        migrations.CreateModel(
            name="LoyaltyTier",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=40)),
                ("threshold_points", models.PositiveIntegerField(default=0)),
                ("points_multiplier", models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=5)),
                ("benefits", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tiers", to="loyalty.loyaltyprogram")),
            ],
            options={"ordering": ["threshold_points", "name"]},
        ),
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("code", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("duration_days", models.PositiveIntegerField(default=365)),
                ("points_multiplier", models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=5)),
                ("join_bonus_points", models.PositiveIntegerField(default=0)),
                ("benefits", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("benefit_promotion", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="membership_plans", to="promotions.promotion")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_membership_plans", to=settings.AUTH_USER_MODEL)),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="membership_plans", to="loyalty.loyaltyprogram")),
            ],
            options={"ordering": ["price", "name"]},
        ),
        migrations.CreateModel(
            name="MembershipSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("pending", "En attente"), ("active", "Active"), ("expired", "Expirée"), ("cancelled", "Annulée")], default="pending", max_length=16)),
                ("price_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("activation_source", models.CharField(blank=True, max_length=16)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="activated_loyalty_memberships", to=settings.AUTH_USER_MODEL)),
                ("benefit_code", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="membership_subscriptions", to="promotions.promotioncode")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="loyalty.membershipplan")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="loyalty.loyaltyprogram")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="loyalty_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-requested_at"]},
        ),
        migrations.CreateModel(
            name="LoyaltyAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("points_balance", models.IntegerField(default=0)),
                ("lifetime_earned", models.PositiveIntegerField(default=0)),
                ("lifetime_redeemed", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_tier", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="accounts", to="loyalty.loyaltytier")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="accounts", to="loyalty.loyaltyprogram")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="loyalty_accounts", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="LoyaltyReward",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("points_cost", models.PositiveIntegerField()),
                ("fulfillment_instructions", models.TextField(blank=True)),
                ("max_redemptions_per_member", models.PositiveSmallIntegerField(default=1)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_loyalty_rewards", to=settings.AUTH_USER_MODEL)),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rewards", to="loyalty.loyaltyprogram")),
                ("promotion", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="loyalty_rewards", to="promotions.promotion")),
            ],
            options={"ordering": ["points_cost", "name"]},
        ),
        migrations.CreateModel(
            name="LoyaltyRewardRedemption",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(default="redeemed", max_length=16)),
                ("points_cost", models.PositiveIntegerField()),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reward_redemptions", to="loyalty.loyaltyaccount")),
                ("promotion_code", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="loyalty_reward_redemptions", to="promotions.promotioncode")),
                ("reward", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="redemptions", to="loyalty.loyaltyreward")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="loyalty_reward_redemptions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-redeemed_at"]},
        ),
        migrations.CreateModel(
            name="LoyaltyLedgerEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("order", "Commande"), ("order_reversal", "Annulation commande"), ("checkin", "Check-in"), ("membership_bonus", "Bonus membership"), ("reward", "Récompense"), ("adjustment", "Ajustement")], max_length=32)),
                ("points", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
                ("idempotency_key", models.CharField(max_length=180, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="loyalty.loyaltyaccount")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_loyalty_ledger_entries", to=settings.AUTH_USER_MODEL)),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="loyalty_ledger_entries", to="tickets.ticketorder")),
                ("reward_redemption", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ledger_entries", to="loyalty.loyaltyrewardredemption")),
                ("subscription", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ledger_entries", to="loyalty.membershipsubscription")),
                ("ticket", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="loyalty_ledger_entries", to="tickets.ticket")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(model_name="loyaltytier", constraint=models.UniqueConstraint(fields=("program", "code"), name="loyalty_tier_program_code_unique")),
        migrations.AddConstraint(model_name="loyaltytier", constraint=models.UniqueConstraint(fields=("program", "threshold_points"), name="loyalty_tier_threshold_unique")),
        migrations.AddConstraint(model_name="membershipplan", constraint=models.UniqueConstraint(fields=("program", "code"), name="membership_plan_program_code_unique")),
        migrations.AddConstraint(model_name="membershipsubscription", constraint=models.UniqueConstraint(condition=Q(status__in=["pending", "active"]), fields=("program", "user"), name="membership_one_current_program_user")),
        migrations.AddIndex(model_name="membershipsubscription", index=models.Index(fields=["program", "status"], name="membership_program_status_idx")),
        migrations.AddIndex(model_name="membershipsubscription", index=models.Index(fields=["ends_at", "status"], name="membership_end_status_idx")),
        migrations.AddConstraint(model_name="loyaltyaccount", constraint=models.UniqueConstraint(fields=("program", "user"), name="loyalty_account_program_user_unique")),
        migrations.AddIndex(model_name="loyaltyaccount", index=models.Index(fields=["program", "points_balance"], name="loyalty_account_balance_idx")),
        migrations.AddIndex(model_name="loyaltyrewardredemption", index=models.Index(fields=["reward", "user", "status"], name="loyalty_reward_user_idx")),
        migrations.AddConstraint(model_name="loyaltyledgerentry", constraint=models.CheckConstraint(condition=~Q(points=0), name="loyalty_ledger_points_nonzero")),
        migrations.AddIndex(model_name="loyaltyledgerentry", index=models.Index(fields=["account", "created_at"], name="loyalty_ledger_account_idx")),
    ]
