# Generated by Django 5.2.14 on 2026-08-09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationFollow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("notify_new_events", models.BooleanField(default=True)),
                ("notify_announcements", models.BooleanField(default=True)),
                ("email_new_events", models.BooleanField(default=False)),
                ("email_announcements", models.BooleanField(default=False)),
                ("followed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="followers", to="organizations.organization")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="followed_organizations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-followed_at"]},
        ),
        migrations.AddConstraint(
            model_name="organizationfollow",
            constraint=models.UniqueConstraint(fields=("organization", "user"), name="organization_follow_unique_user"),
        ),
        migrations.AddIndex(
            model_name="organizationfollow",
            index=models.Index(fields=["organization", "followed_at"], name="org_follow_org_date_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationfollow",
            index=models.Index(fields=["user", "followed_at"], name="org_follow_user_date_idx"),
        ),
    ]
