from django.urls import path

from .product_views import ProductOperationsDashboardView
from .subscription_views import (
    OperationsEntitlementGrantCreateView,
    OperationsEntitlementGrantRevokeView,
    OperationsEntitlementRequirementCreateView,
    OperationsEntitlementRequirementDeleteView,
    OperationsPlanBenefitCreateView,
    OperationsPlanBenefitDeleteView,
    OperationsPlanEntitlementCreateView,
    OperationsPlanEntitlementDeleteView,
    OperationsPlanRequirementCreateView,
    OperationsPlanRequirementDeleteView,
    OperationsPlanVersionCreateView,
    OperationsPlanVersionPublishView,
    OperationsPlanVersionRetireView,
    OperationsPlanVersionUpdateView,
    OperationsPlanVersionView,
    OperationsSubscriptionCatalogView,
    OperationsSubscriptionHubView,
    OperationsSubscriptionPlanCreateView,
    OperationsSubscriptionPlanView,
    OperationsSubscriptionReviewDecisionView,
    OperationsSubscriptionReviewQueueView,
    OperationsSubscriptionSupportDetailView,
    OperationsSubscriptionSupportListView,
    OperationsSubscriptionTransitionCancelView,
    OperationsSubscriptionTransitionCompleteView,
)
from .views import (
    EventModerationView,
    ModerationQueueView,
    OperationsEventsView,
    OperationsIncidentCreateView,
    OperationsIncidentDetailView,
    OperationsIncidentsView,
    OperationsOrganizationsView,
    OrganizationReviewView,
)


app_name = "operations"

urlpatterns = [
    path("", ProductOperationsDashboardView.as_view(), name="dashboard"),
    path("subscriptions/", OperationsSubscriptionHubView.as_view(), name="subscriptions"),
    path("subscriptions/catalog/", OperationsSubscriptionCatalogView.as_view(), name="subscription-catalog"),
    path("subscriptions/catalog/plans/new/", OperationsSubscriptionPlanCreateView.as_view(), name="subscription-plan-create"),
    path("subscriptions/catalog/plans/<uuid:plan_id>/", OperationsSubscriptionPlanView.as_view(), name="subscription-plan"),
    path("subscriptions/catalog/plans/<uuid:plan_id>/versions/new/", OperationsPlanVersionCreateView.as_view(), name="subscription-version-create"),
    path("subscriptions/catalog/versions/<uuid:version_id>/", OperationsPlanVersionView.as_view(), name="subscription-version"),
    path("subscriptions/catalog/versions/<uuid:version_id>/edit/", OperationsPlanVersionUpdateView.as_view(), name="subscription-version-edit"),
    path("subscriptions/catalog/versions/<uuid:version_id>/publish/", OperationsPlanVersionPublishView.as_view(), name="subscription-version-publish"),
    path("subscriptions/catalog/versions/<uuid:version_id>/retire/", OperationsPlanVersionRetireView.as_view(), name="subscription-version-retire"),
    path("subscriptions/catalog/versions/<uuid:version_id>/benefits/new/", OperationsPlanBenefitCreateView.as_view(), name="subscription-benefit-create"),
    path("subscriptions/catalog/versions/<uuid:version_id>/benefits/<uuid:benefit_id>/delete/", OperationsPlanBenefitDeleteView.as_view(), name="subscription-benefit-delete"),
    path("subscriptions/catalog/versions/<uuid:version_id>/entitlements/new/", OperationsPlanEntitlementCreateView.as_view(), name="subscription-entitlement-create"),
    path("subscriptions/catalog/versions/<uuid:version_id>/entitlements/<uuid:entitlement_id>/delete/", OperationsPlanEntitlementDeleteView.as_view(), name="subscription-entitlement-delete"),
    path("subscriptions/catalog/versions/<uuid:version_id>/requirements/new/", OperationsPlanRequirementCreateView.as_view(), name="subscription-requirement-create"),
    path("subscriptions/catalog/versions/<uuid:version_id>/requirements/<uuid:requirement_id>/delete/", OperationsPlanRequirementDeleteView.as_view(), name="subscription-requirement-delete"),
    path("subscriptions/catalog/versions/<uuid:version_id>/entitlements/<uuid:entitlement_id>/requirements/new/", OperationsEntitlementRequirementCreateView.as_view(), name="subscription-entitlement-requirement-create"),
    path("subscriptions/catalog/versions/<uuid:version_id>/entitlements/<uuid:entitlement_id>/requirements/<uuid:requirement_id>/delete/", OperationsEntitlementRequirementDeleteView.as_view(), name="subscription-entitlement-requirement-delete"),
    path("subscriptions/support/", OperationsSubscriptionSupportListView.as_view(), name="subscription-support"),
    path("subscriptions/support/<uuid:subscription_id>/", OperationsSubscriptionSupportDetailView.as_view(), name="subscription-detail"),
    path("subscriptions/support/<uuid:subscription_id>/grants/new/", OperationsEntitlementGrantCreateView.as_view(), name="subscription-grant-create"),
    path("subscriptions/support/<uuid:subscription_id>/grants/<uuid:grant_id>/revoke/", OperationsEntitlementGrantRevokeView.as_view(), name="subscription-grant-revoke"),
    path("subscriptions/reviews/", OperationsSubscriptionReviewQueueView.as_view(), name="subscription-reviews"),
    path("subscriptions/reviews/<uuid:assessment_id>/decide/", OperationsSubscriptionReviewDecisionView.as_view(), name="subscription-review-decide"),
    path("subscriptions/support/<uuid:subscription_id>/transitions/<uuid:transition_id>/cancel/", OperationsSubscriptionTransitionCancelView.as_view(), name="subscription-transition-cancel"),
    path("subscriptions/support/<uuid:subscription_id>/transitions/<uuid:transition_id>/complete/", OperationsSubscriptionTransitionCompleteView.as_view(), name="subscription-transition-complete"),
    path("organizations/", OperationsOrganizationsView.as_view(), name="organizations"),
    path("organizations/<uuid:pk>/review/", OrganizationReviewView.as_view(), name="organization-review"),
    path("events/", OperationsEventsView.as_view(), name="events"),
    path("events/<uuid:pk>/moderate/", EventModerationView.as_view(), name="event-moderate"),
    path("incidents/", OperationsIncidentsView.as_view(), name="incidents"),
    path("incidents/new/", OperationsIncidentCreateView.as_view(), name="incident-new"),
    path("incidents/<uuid:pk>/", OperationsIncidentDetailView.as_view(), name="incident-detail"),
    path("moderation/", ModerationQueueView.as_view(), name="moderation"),
]
