from django.urls import path

from .community_views import (
    ActivityEligibilityApproveView,
    ActivityEligibilityRejectView,
    ActivityEligibilityRequestView,
    ActivityEligibilityReviewView,
    ActivityEligibilityRevokeView,
    CommunityGroupCreateView,
    CommunityGroupDetailView,
    CommunityGroupEditView,
    CommunityGroupListView,
    CommunityGroupMembersView,
    GroupExploreView,
    GroupJoinRequestApproveView,
    GroupJoinRequestCancelView,
    GroupJoinRequestCreateView,
    GroupJoinRequestRejectView,
    GroupJoinView,
)
from .views import (
    GroupAddMemberView,
    GroupArchiveView,
    GroupImportView,
    GroupInvitationClaimView,
    GroupInviteView,
    GroupLeaveView,
    GroupRemoveMemberView,
    GroupResponsibilityView,
    GroupRevokeInvitationView,
    GroupSnapshotCreateView,
    GroupSuspendMemberView,
    GroupTransferOwnershipView,
)


app_name = "groups"

urlpatterns = [
    path("", CommunityGroupListView.as_view(), name="list"),
    path("explore/", GroupExploreView.as_view(), name="explore"),
    path("new/", CommunityGroupCreateView.as_view(), name="create"),
    path("join-requests/<uuid:request_id>/cancel/", GroupJoinRequestCancelView.as_view(), name="join-request-cancel"),
    path("activity-eligibilities/<uuid:eligibility_id>/", ActivityEligibilityReviewView.as_view(), name="activity-eligibility-review"),
    path("activity-eligibilities/<uuid:eligibility_id>/approve/", ActivityEligibilityApproveView.as_view(), name="activity-eligibility-approve"),
    path("activity-eligibilities/<uuid:eligibility_id>/reject/", ActivityEligibilityRejectView.as_view(), name="activity-eligibility-reject"),
    path("activity-eligibilities/<uuid:eligibility_id>/revoke/", ActivityEligibilityRevokeView.as_view(), name="activity-eligibility-revoke"),
    path("invitations/<str:token>/", GroupInvitationClaimView.as_view(), name="invitation"),
    path("<slug:slug>/", CommunityGroupDetailView.as_view(), name="detail"),
    path("<slug:slug>/edit/", CommunityGroupEditView.as_view(), name="edit"),
    path("<slug:slug>/members/", CommunityGroupMembersView.as_view(), name="members"),
    path("<slug:slug>/join/", GroupJoinView.as_view(), name="join"),
    path("<slug:slug>/join-request/", GroupJoinRequestCreateView.as_view(), name="join-request"),
    path("<slug:slug>/join-requests/<uuid:request_id>/approve/", GroupJoinRequestApproveView.as_view(), name="join-request-approve"),
    path("<slug:slug>/join-requests/<uuid:request_id>/reject/", GroupJoinRequestRejectView.as_view(), name="join-request-reject"),
    path("<slug:slug>/activity-eligibilities/request/", ActivityEligibilityRequestView.as_view(), name="activity-eligibility-request"),
    path("<slug:slug>/members/add/", GroupAddMemberView.as_view(), name="member-add"),
    path("<slug:slug>/members/<uuid:profile_id>/suspend/", GroupSuspendMemberView.as_view(), name="member-suspend"),
    path("<slug:slug>/members/<uuid:profile_id>/remove/", GroupRemoveMemberView.as_view(), name="member-remove"),
    path("<slug:slug>/leave/", GroupLeaveView.as_view(), name="leave"),
    path("<slug:slug>/invite/", GroupInviteView.as_view(), name="invite"),
    path("<slug:slug>/invitations/<uuid:invitation_id>/revoke/", GroupRevokeInvitationView.as_view(), name="invitation-revoke"),
    path("<slug:slug>/import/", GroupImportView.as_view(), name="import"),
    path("<slug:slug>/snapshots/create/", GroupSnapshotCreateView.as_view(), name="snapshot-create"),
    path("<slug:slug>/archive/", GroupArchiveView.as_view(), name="archive"),
    path("<slug:slug>/transfer/", GroupTransferOwnershipView.as_view(), name="transfer"),
    path("<slug:slug>/responsibilities/", GroupResponsibilityView.as_view(), name="responsibility"),
]
