# Generated by Django 5.2.14 on 2026-08-09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmcontact",
            name="source",
            field=models.CharField(choices=[("ticket_order", "Commande"), ("ticket", "Billet"), ("waitlist", "Liste d’attente"), ("follower", "Abonné organisateur"), ("manual", "Manuel")], default="ticket_order", max_length=24),
        ),
        migrations.AlterField(
            model_name="audiencesegment",
            name="audience_kind",
            field=models.CharField(choices=[("all", "Tous les contacts"), ("followers", "Abonnés de l’organisateur"), ("confirmed_buyers", "Acheteurs confirmés"), ("ticket_holders", "Détenteurs de billets"), ("attendees", "Participants présents"), ("no_shows", "Absents / no-show"), ("waitlist", "Liste d’attente"), ("partner_referred", "Acquisition partenaire")], default="all", max_length=32),
        ),
        migrations.CreateModel(
            name="CRMTag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("color", models.CharField(default="indigo", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_crm_tags", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="crm_tags", to="organizations.organization")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddConstraint(
            model_name="crmtag",
            constraint=models.UniqueConstraint(fields=("organization", "name"), name="crm_tag_org_name_unique"),
        ),
        migrations.CreateModel(
            name="CRMCustomField",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=120)),
                ("field_type", models.CharField(choices=[("text", "Texte"), ("number", "Nombre"), ("boolean", "Oui / Non"), ("date", "Date"), ("select", "Liste de choix")], default="text", max_length=16)),
                ("options", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_crm_custom_fields", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="crm_custom_fields", to="organizations.organization")),
            ],
            options={"ordering": ["label"]},
        ),
        migrations.AddConstraint(
            model_name="crmcustomfield",
            constraint=models.UniqueConstraint(fields=("organization", "key"), name="crm_custom_field_org_key_unique"),
        ),
        migrations.CreateModel(
            name="CampaignTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("kind", models.CharField(choices=[("marketing", "Marketing"), ("event_update", "Information événement")], default="marketing", max_length=20)),
                ("subject", models.CharField(max_length=180)),
                ("preview_text", models.CharField(blank=True, max_length=220)),
                ("body", models.TextField()),
                ("cta_label", models.CharField(blank=True, max_length=80)),
                ("cta_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_crm_campaign_templates", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="crm_campaign_templates", to="organizations.organization")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddConstraint(
            model_name="campaigntemplate",
            constraint=models.UniqueConstraint(fields=("organization", "name"), name="crm_template_org_name_unique"),
        ),
        migrations.AddField(
            model_name="audiencesegment",
            name="custom_filters",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="audiencesegment",
            name="required_tags",
            field=models.ManyToManyField(blank=True, related_name="segments", to="crm.crmtag"),
        ),
        migrations.AddField(
            model_name="communicationcampaign",
            name="attribution_window_days",
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name="communicationcampaign",
            name="template",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="campaigns", to="crm.campaigntemplate"),
        ),
        migrations.AddField(
            model_name="communicationcampaign",
            name="track_conversions",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(model_name="campaignrecipient", name="click_count", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name="campaignrecipient", name="first_clicked_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="campaignrecipient", name="last_clicked_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.CreateModel(
            name="CRMContactTag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_crm_tags", to=settings.AUTH_USER_MODEL)),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tag_links", to="crm.crmcontact")),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contact_links", to="crm.crmtag")),
            ],
        ),
        migrations.AddConstraint(model_name="crmcontacttag", constraint=models.UniqueConstraint(fields=("contact", "tag"), name="crm_contact_tag_unique")),
        migrations.AddIndex(model_name="crmcontacttag", index=models.Index(fields=["tag", "contact"], name="crm_contact_tag_lookup_idx")),
        migrations.CreateModel(
            name="CRMContactFieldValue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("value", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="custom_values", to="crm.crmcontact")),
                ("field", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contact_values", to="crm.crmcustomfield")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_crm_custom_values", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(model_name="crmcontactfieldvalue", constraint=models.UniqueConstraint(fields=("contact", "field"), name="crm_contact_field_value_unique")),
        migrations.AddIndex(model_name="crmcontactfieldvalue", index=models.Index(fields=["field", "contact"], name="crm_field_value_lookup_idx")),
        migrations.CreateModel(
            name="CampaignAttribution",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("pending", "En attente"), ("confirmed", "Conversion confirmée"), ("reversed", "Conversion annulée")], default="pending", max_length=16)),
                ("revenue_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attributions", to="crm.communicationcampaign")),
                ("contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="campaign_attributions", to="crm.crmcontact")),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="crm_campaign_attribution", to="tickets.ticketorder")),
                ("recipient", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="attributions", to="crm.campaignrecipient")),
            ],
            options={"ordering": ["-captured_at"]},
        ),
        migrations.AddIndex(model_name="campaignattribution", index=models.Index(fields=["campaign", "status", "captured_at"], name="crm_attr_campaign_status_idx")),
    ]
