# Generated by Django 5.2.14 on 2026-08-09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAccessGate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("throughput_target_per_minute", models.PositiveSmallIntegerField(default=20, help_text="Débit cible accepté par minute pour détecter la congestion.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)])),
                ("warning_rejection_rate", models.PositiveSmallIntegerField(default=30, help_text="Taux de refus à partir duquel la porte est signalée.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="access_gates_created", to=settings.AUTH_USER_MODEL)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="access_gates", to="events.event")),
            ],
            options={
                "ordering": ["event__start_at", "priority", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="eventaccessgate",
            constraint=models.UniqueConstraint(fields=("event", "slug"), name="scanner_gate_event_slug_unique"),
        ),
        migrations.AddConstraint(
            model_name="eventaccessgate",
            constraint=models.CheckConstraint(condition=models.Q(("throughput_target_per_minute__gt", 0)), name="scan_gate_throughput_positive"),
        ),
        migrations.AddIndex(
            model_name="eventaccessgate",
            index=models.Index(fields=["event", "is_active"], name="scanner_gate_event_active_idx"),
        ),
        migrations.AddIndex(
            model_name="eventaccessgate",
            index=models.Index(fields=["event", "priority"], name="scanner_gate_event_prio_idx"),
        ),
        migrations.AddField(
            model_name="scannerassignment",
            name="access_gate",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assignments", to="scanner.eventaccessgate"),
        ),
        migrations.AddField(
            model_name="scanlog",
            name="access_gate",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="scan_logs", to="scanner.eventaccessgate"),
        ),
        migrations.AlterField(
            model_name="scanlog",
            name="result",
            field=models.CharField(choices=[("accepted", "Accès autorisé"), ("duplicate", "Billet déjà utilisé"), ("invalid_token", "QR invalide"), ("unknown_ticket", "Billet introuvable"), ("wrong_event", "Mauvais événement"), ("invalid_status", "Billet non valide"), ("event_unavailable", "Événement indisponible"), ("gate_unavailable", "Porte indisponible")], max_length=32),
        ),
        migrations.AddIndex(
            model_name="scanlog",
            index=models.Index(fields=["access_gate", "scanned_at"], name="scanner_gate_time_idx"),
        ),
    ]
