# Generated by Django 5.2.14 on 2026-08-07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketOrder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference", models.CharField(editable=False, max_length=24, unique=True)),
                ("customer_name", models.CharField(max_length=180)),
                ("customer_email", models.EmailField(max_length=254)),
                ("status", models.CharField(choices=[("pending", "En attente"), ("confirmed", "Confirmée"), ("cancelled", "Annulée"), ("expired", "Expirée")], default="pending", max_length=20)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("buyer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ticket_orders", to=settings.AUTH_USER_MODEL)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ticket_orders", to="events.event")),
            ],
            options={
                "verbose_name": "commande de billets",
                "verbose_name_plural": "commandes de billets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=140)),
                ("slug", models.SlugField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("quantity_total", models.PositiveIntegerField(blank=True, help_text="Laisser vide pour un stock illimité.", null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ("reserved_quantity", models.PositiveIntegerField(default=0, editable=False)),
                ("issued_quantity", models.PositiveIntegerField(default=0, editable=False)),
                ("sales_start_at", models.DateTimeField(blank=True, null=True)),
                ("sales_end_at", models.DateTimeField(blank=True, null=True)),
                ("min_per_order", models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ("max_per_order", models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ticket_types", to="events.event")),
            ],
            options={
                "verbose_name": "type de billet",
                "verbose_name_plural": "types de billets",
                "ordering": ["price", "name"],
            },
        ),
        migrations.CreateModel(
            name="TicketOrderItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="tickets.ticketorder")),
                ("ticket_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="order_items", to="tickets.tickettype")),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("holder_name", models.CharField(max_length=180)),
                ("holder_email", models.EmailField(max_length=254)),
                ("status", models.CharField(choices=[("valid", "Valide"), ("used", "Utilisé"), ("cancelled", "Annulé"), ("refunded", "Remboursé")], default="valid", max_length=20)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="events.event")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="tickets.ticketorder")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tickets", to=settings.AUTH_USER_MODEL)),
                ("ticket_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="tickets.tickettype")),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="tickettype",
            constraint=models.UniqueConstraint(fields=("event", "slug"), name="ticket_type_event_slug_unique"),
        ),
        migrations.AddConstraint(
            model_name="ticketorderitem",
            constraint=models.UniqueConstraint(fields=("order", "ticket_type"), name="ticket_order_item_type_unique"),
        ),
        migrations.AddIndex(
            model_name="ticketorder",
            index=models.Index(fields=["event", "status"], name="tickets_tic_event_i_90a056_idx"),
        ),
        migrations.AddIndex(
            model_name="ticketorder",
            index=models.Index(fields=["buyer", "status"], name="tickets_tic_buyer_i_a16f5d_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["event", "status"], name="tickets_tic_event_i_d6dbab_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["owner", "status"], name="tickets_tic_owner_i_b7d868_idx"),
        ),
    ]
