"""Executable long-horizon multi-galaxy scenario built from the compact catalogue."""
from __future__ import annotations

from dataclasses import dataclass, field
import numpy as np

from ..constants import C, JULIAN_YEAR
from ..values import Instant
from ..simulation.large_scale_engine import DomainePopulationClassique, DomainePopulationSR
from ..simulation.large_scale_multirate import SimulationGrandeEchelleMultiTaux
from ..simulation.multirate import CadenceEvolution
from .multigalaxy_catalogue import CatalogueMultiGalaxies, generer_catalogue_multi_galaxies


@dataclass(slots=True)
class ProgrammePropulsionSRMultiGalaxies:
    """Piecewise collinear SR thrust program expressed as physical dp/dt.

    Mission codes are generated by the catalogue:
    0 coast, 1 early acceleration, 2 acceleration then late deceleration,
    3 late deceleration. The requested rapidity change is converted into a
    constant coordinate three-force over the scheduled coordinate-time window
    using p = m c sinh(eta). The SR integrator remains responsible for v(p).
    """

    catalogue: CatalogueMultiGalaxies
    duree_mission_s: float
    instant_depart_s: float = 0.0
    _direction: np.ndarray = field(init=False, repr=False)
    _plus_par_masse: np.ndarray = field(init=False, repr=False)
    _moins_symetrique_par_masse: np.ndarray = field(init=False, repr=False)
    _moins_seul_par_masse: np.ndarray = field(init=False, repr=False)

    def __post_init__(self) -> None:
        if self.duree_mission_s <= 0:
            raise ValueError("Mission duration must be positive")
        ship_slice = self.catalogue.tranches["ships"]
        velocity = self.catalogue.vitesses_locales_m_s[ship_slice]
        speed = np.linalg.norm(velocity, axis=1)
        self._direction = velocity / speed[:, None]
        eta0 = np.arctanh(self.catalogue.beta_vaisseaux)
        delta = self.catalogue.delta_rapidite_vaisseaux
        fa = self.catalogue.fraction_acceleration_vaisseaux
        fd = self.catalogue.fraction_deceleration_vaisseaux
        self._plus_par_masse = C * (np.sinh(eta0 + delta) - np.sinh(eta0)) / (fa * self.duree_mission_s)
        self._moins_symetrique_par_masse = C * (np.sinh(eta0 + delta) - np.sinh(eta0)) / (fd * self.duree_mission_s)
        eta_cible = np.maximum(eta0 - delta, 0.0)
        self._moins_seul_par_masse = C * (np.sinh(eta0) - np.sinh(eta_cible)) / (fd * self.duree_mission_s)

    def __call__(self, backend, instant: Instant) -> np.ndarray:
        count = len(self.catalogue.beta_vaisseaux)
        if len(backend.body_ids) != count:
            raise ValueError("Thrust program does not match SR vehicle backend")
        phase = (instant.seconds - self.instant_depart_s) / self.duree_mission_s
        force_per_mass = np.zeros(count, dtype=np.float64)
        if 0.0 <= phase <= 1.0:
            modes = self.catalogue.modes_mission_vaisseaux
            fa = self.catalogue.fraction_acceleration_vaisseaux
            fd = self.catalogue.fraction_deceleration_vaisseaux
            accelerating = ((modes == 1) | (modes == 2)) & (phase < fa)
            force_per_mass[accelerating] = self._plus_par_masse[accelerating]
            symmetric_braking = (modes == 2) & (phase >= 1.0 - fd)
            force_per_mass[symmetric_braking] = -self._moins_symetrique_par_masse[symmetric_braking]
            braking_only = (modes == 3) & (phase >= 1.0 - fd)
            force_per_mass[braking_only] = -self._moins_seul_par_masse[braking_only]
        forces = self._direction * (backend.masses_kg * force_per_mass)[:, None]
        forces[~backend.masque_evolution()] = 0.0
        return forces


@dataclass(slots=True)
class ScenarioMultiGalaxies:
    catalogue: CatalogueMultiGalaxies
    duree_s: float
    simulation: SimulationGrandeEchelleMultiTaux
    galaxies: DomainePopulationClassique
    vaisseaux: DomainePopulationSR
    propulsion: ProgrammePropulsionSRMultiGalaxies

    def executer(self) -> dict[str, object]:
        self.simulation.executer(self.duree_s)
        return self.resume()

    def resume(self) -> dict[str, object]:
        if not self.simulation.simultanes(max(1e-6, abs(self.duree_s) * 1e-12)):
            raise RuntimeError("Scenario summary requires a common coordinate-time barrier")
        self.vaisseaux.backend.rafraichir_vitesses()
        speed = np.linalg.norm(self.vaisseaux.backend.velocities_m_s, axis=1)
        proper = self.vaisseaux.backend.proper_times_s
        start = self.catalogue.positions_locales_m[self.catalogue.tranches["ships"]]
        distance = np.linalg.norm(self.vaisseaux.backend.positions_m - start, axis=1)
        galaxy_shift = np.linalg.norm(
            self.galaxies.backend.positions_m - self.catalogue.positions_galaxies_m,
            axis=1,
        )
        modes, mode_counts = np.unique(self.catalogue.modes_mission_vaisseaux, return_counts=True)
        return {
            "scale": self.catalogue.configuration.nom,
            "catalogue_entities": self.catalogue.nombre_entites,
            "catalogue_memory_bytes": self.catalogue.memoire_tableaux_octets(),
            "coordinate_time_s": self.simulation.instant_barriere.seconds,
            "coordinate_time_years": self.simulation.instant_barriere.seconds / JULIAN_YEAR,
            "galaxies": self.catalogue.configuration.nombre_galaxies,
            "stellar_systems": self.catalogue.configuration.nombre_systemes,
            "sr_vehicles": len(self.vaisseaux.backend.body_ids),
            "intergalactic_missions": int(np.count_nonzero(self.catalogue.cibles_systemes_vaisseaux < 0)),
            "mission_modes": {str(int(mode)): int(count) for mode, count in zip(modes, mode_counts)},
            "beta_min": float(np.min(speed / C)),
            "beta_median": float(np.median(speed / C)),
            "beta_max": float(np.max(speed / C)),
            "proper_time_min_years": float(np.min(proper) / JULIAN_YEAR),
            "proper_time_median_years": float(np.median(proper) / JULIAN_YEAR),
            "proper_time_max_years": float(np.max(proper) / JULIAN_YEAR),
            "distance_median_pc": float(np.median(distance) / 3.085677581491367e16),
            "distance_max_pc": float(np.max(distance) / 3.085677581491367e16),
            "galaxy_max_displacement_pc": float(np.max(galaxy_shift) / 3.085677581491367e16),
            "schedule_deadlines": self.simulation.echeances_executees,
        }


def construire_scenario_multi_galaxies(
    echelle: str = "mini",
    duree_annees: float = 10_000.0,
    *,
    pas_vaisseaux_annees: float | None = None,
    pas_galaxies_annees: float | None = None,
) -> ScenarioMultiGalaxies:
    if duree_annees <= 0:
        raise ValueError("Scenario duration must be positive")
    catalogue = generer_catalogue_multi_galaxies(echelle)
    duration = float(duree_annees) * JULIAN_YEAR
    ship_step_years = (
        max(0.1, min(500.0, duree_annees / 10_000.0))
        if pas_vaisseaux_annees is None
        else float(pas_vaisseaux_annees)
    )
    galaxy_step_years = (
        max(10.0, min(5_000.0, duree_annees / 1_000.0))
        if pas_galaxies_annees is None
        else float(pas_galaxies_annees)
    )
    if ship_step_years <= 0 or galaxy_step_years <= 0:
        raise ValueError("Domain cadences must be positive")

    galaxy_domain = DomainePopulationClassique("galaxies", catalogue.backend_galaxies())
    propulsion = ProgrammePropulsionSRMultiGalaxies(catalogue, duration)
    ship_domain = DomainePopulationSR(
        "vaisseaux-sr",
        catalogue.backend_vaisseaux_sr(),
        force_provider=propulsion,
    )
    cadences = {
        galaxy_domain.nom: CadenceEvolution(galaxy_domain.nom, galaxy_step_years * JULIAN_YEAR),
        ship_domain.nom: CadenceEvolution(ship_domain.nom, ship_step_years * JULIAN_YEAR),
    }
    simulation = SimulationGrandeEchelleMultiTaux(
        Instant(0.0),
        [galaxy_domain, ship_domain],
        cadences,
    )
    return ScenarioMultiGalaxies(
        catalogue,
        duration,
        simulation,
        galaxy_domain,
        ship_domain,
        propulsion,
    )
