from django.urls import include, path

from transport.console_views import (
    TransportConsoleCreateDepartureView,
    TransportConsoleCreateRouteView,
    TransportConsoleCreateVehicleView,
    TransportConsoleDepartureDetailView,
    TransportConsoleRouteDetailView,
    TransportConsoleView,
)

from .console_access import SpaceConsoleAccessView, SpaceConsoleGrantAccessView
from .console_scanner import SpaceActivityScannerAPIView, SpaceActivityScannerView
from .console_views import (
    SpaceAccessRevokeView,
    SpaceConsoleActivitiesView,
    SpaceConsoleActivityDetailView,
    SpaceConsoleAnalyticsView,
    SpaceConsoleAudiencesView,
    SpaceConsoleAutomationView,
    SpaceConsoleControlView,
    SpaceConsoleCreateEventView,
    SpaceConsoleCRMView,
    SpaceConsoleEntryView,
    SpaceConsoleGroupsView,
    SpaceConsoleOffersView,
    SpaceConsoleOperationsView,
    SpaceConsoleOrdersView,
    SpaceConsoleOverviewView,
    SpaceConsolePaymentsView,
    SpaceConsolePlacesView,
    SpaceConsolePromotionsView,
    SpaceConsoleSettingsView,
    SpaceConsoleTeamView,
    SpaceConsoleRequestsView,
    SpaceRequestApproveView,
    SpaceRequestRejectView,
)
from .team_views import OrganizationMemberCreateView, OrganizationMemberDeactivateView, SpaceConsoleMemberResponsibilitiesView
from .views import FollowingListView, OrganizationCreateView, OrganizationListView, OrganizationUpdateView

app_name = "organizations"

urlpatterns = [
    path("", OrganizationListView.as_view(), name="list"),
    path("following/", FollowingListView.as_view(), name="following"),
    path("new/", OrganizationCreateView.as_view(), name="create"),
    path("<slug:slug>/", SpaceConsoleEntryView.as_view(), name="console-entry"),
    path("<slug:slug>/overview/", SpaceConsoleOverviewView.as_view(), name="console-overview"),
    path("<slug:slug>/activities/", SpaceConsoleActivitiesView.as_view(), name="console-activities"),
    path("<slug:slug>/activities/new/event/", SpaceConsoleCreateEventView.as_view(), name="console-create-event"),
    path("<slug:slug>/activities/<uuid:activity_id>/", SpaceConsoleActivityDetailView.as_view(), name="console-activity-detail"),
    path("<slug:slug>/transport/", TransportConsoleView.as_view(), name="console-transport"),
    path("<slug:slug>/transport/routes/new/", TransportConsoleCreateRouteView.as_view(), name="console-transport-route-create"),
    path("<slug:slug>/transport/routes/<uuid:route_id>/", TransportConsoleRouteDetailView.as_view(), name="console-transport-route-detail"),
    path("<slug:slug>/transport/vehicles/new/", TransportConsoleCreateVehicleView.as_view(), name="console-transport-vehicle-create"),
    path("<slug:slug>/transport/departures/new/", TransportConsoleCreateDepartureView.as_view(), name="console-transport-departure-create"),
    path("<slug:slug>/transport/departures/<uuid:departure_id>/", TransportConsoleDepartureDetailView.as_view(), name="console-transport-departure-detail"),
    path("<slug:slug>/requests/", SpaceConsoleRequestsView.as_view(), name="console-requests"),
    path("<slug:slug>/requests/<uuid:request_id>/approve/", SpaceRequestApproveView.as_view(), name="console-request-approve"),
    path("<slug:slug>/requests/<uuid:request_id>/reject/", SpaceRequestRejectView.as_view(), name="console-request-reject"),
    path("<slug:slug>/access/", SpaceConsoleAccessView.as_view(), name="console-access"),
    path("<slug:slug>/access/grant/", SpaceConsoleGrantAccessView.as_view(), name="console-access-grant"),
    path("<slug:slug>/access/<uuid:access_id>/revoke/", SpaceAccessRevokeView.as_view(), name="console-access-revoke"),
    path("<slug:slug>/offers/", SpaceConsoleOffersView.as_view(), name="console-offers"),
    path("<slug:slug>/orders/", SpaceConsoleOrdersView.as_view(), name="console-orders"),
    path("<slug:slug>/payments/", SpaceConsolePaymentsView.as_view(), name="console-payments"),
    path("<slug:slug>/groups/", SpaceConsoleGroupsView.as_view(), name="console-groups"),
    path("<slug:slug>/crm/", SpaceConsoleCRMView.as_view(), name="console-crm"),
    path("<slug:slug>/audiences/", SpaceConsoleAudiencesView.as_view(), name="console-audiences"),
    path("<slug:slug>/promotions/", SpaceConsolePromotionsView.as_view(), name="console-promotions"),
    path("<slug:slug>/places/", SpaceConsolePlacesView.as_view(), name="console-places"),
    path("<slug:slug>/control/", SpaceConsoleControlView.as_view(), name="console-control"),
    path("<slug:slug>/control/<uuid:activity_id>/", SpaceActivityScannerView.as_view(), name="console-control-activity"),
    path("<slug:slug>/control/<uuid:activity_id>/scan/", SpaceActivityScannerAPIView.as_view(), name="console-control-activity-scan"),
    path("<slug:slug>/operations/", SpaceConsoleOperationsView.as_view(), name="console-operations"),
    path("<slug:slug>/analytics/", SpaceConsoleAnalyticsView.as_view(), name="console-analytics"),
    path("<slug:slug>/automation/", SpaceConsoleAutomationView.as_view(), name="console-automation"),
    path("<slug:slug>/team/", SpaceConsoleTeamView.as_view(), name="console-team"),
    path("<slug:slug>/team/add/", OrganizationMemberCreateView.as_view(), name="team-member-create"),
    path("<slug:slug>/team/<uuid:membership_id>/responsibilities/", SpaceConsoleMemberResponsibilitiesView.as_view(), name="member-responsibilities"),
    path("<slug:slug>/team/<uuid:pk>/deactivate/", OrganizationMemberDeactivateView.as_view(), name="member-deactivate"),
    path("<slug:slug>/settings/", SpaceConsoleSettingsView.as_view(), name="console-settings"),
    path("<slug:slug>/settings/edit/", OrganizationUpdateView.as_view(), name="edit"),
    path("", include("geography.urls")),
]
