# Generated for Task 12 — canonical Transport vertical.
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("activities", "0002_occurrence_place"), ("capacity", "0001_initial"), ("geography", "0001_initial"), ("organizations", "0003_team_teammembership")]
    operations = [
        migrations.CreateModel(name="TransportRoute", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("code", models.CharField(blank=True, max_length=48)), ("name", models.CharField(max_length=180)), ("active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("space", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transport_routes", to="organizations.organization"))], options={"ordering": ["name", "id"]}),
        migrations.CreateModel(name="Vehicle", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("label", models.CharField(max_length=180)), ("registration", models.CharField(blank=True, max_length=80)), ("vehicle_type", models.CharField(choices=[("bus", "Bus / autocar"), ("minibus", "Minibus"), ("van", "Van"), ("car", "Voiture"), ("other", "Autre")], default="bus", max_length=16)), ("passenger_capacity", models.PositiveIntegerField()), ("active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("space", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transport_vehicles", to="organizations.organization"))], options={"ordering": ["label", "id"]}),
        migrations.CreateModel(name="TransportService", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("mode", models.CharField(choices=[("road", "Route"), ("air", "Air"), ("rail", "Rail"), ("water", "Eau"), ("other", "Autre")], default="road", max_length=16)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("activity", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="transport_service", to="activities.activity")), ("route", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="services", to="transport.transportroute"))]),
        migrations.CreateModel(name="TransportRouteStop", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("position", models.PositiveSmallIntegerField()), ("boarding_allowed", models.BooleanField(default=True)), ("alighting_allowed", models.BooleanField(default=True)), ("notes", models.CharField(blank=True, max_length=320)), ("place", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transport_route_stops", to="geography.place")), ("route", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stops", to="transport.transportroute"))], options={"ordering": ["position", "id"]}),
        migrations.CreateModel(name="TransportDeparture", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("boarding_instructions", models.CharField(blank=True, max_length=320)), ("operational_reference", models.CharField(blank=True, max_length=80)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("occurrence", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="transport_departure", to="activities.occurrence")), ("passenger_capacity_pool", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="transport_departure", to="capacity.capacitypool")), ("vehicle", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="departures", to="transport.vehicle"))]),
        migrations.AddIndex(model_name="transportroute", index=models.Index(fields=["space", "active"], name="transport_route_space_idx")),
        migrations.AddConstraint(model_name="transportroute", constraint=models.UniqueConstraint(condition=~models.Q(code=""), fields=("space", "code"), name="transport_route_code_unique")),
        migrations.AddIndex(model_name="transportroutestop", index=models.Index(fields=["route", "position"], name="transport_stop_route_idx")),
        migrations.AddConstraint(model_name="transportroutestop", constraint=models.CheckConstraint(condition=models.Q(position__gte=1), name="transport_stop_position_positive")),
        migrations.AddConstraint(model_name="transportroutestop", constraint=models.UniqueConstraint(fields=("route", "position"), name="transport_route_stop_position_unique")),
        migrations.AddIndex(model_name="vehicle", index=models.Index(fields=["space", "active"], name="transport_vehicle_space_idx")),
        migrations.AddConstraint(model_name="vehicle", constraint=models.CheckConstraint(condition=models.Q(passenger_capacity__gt=0), name="transport_vehicle_capacity_positive")),
        migrations.AddIndex(model_name="transportdeparture", index=models.Index(fields=["vehicle"], name="transport_depart_vehicle_idx")),
    ]
