# Generated by Django 5.2 on 2026-09-02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("sharing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("envelope", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="sharing.shareenvelope")),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="share_deliveries_received", to="accounts.userprofile")),
            ],
            options={
                "ordering": ["-delivered_at", "id"],
                "indexes": [models.Index(fields=["recipient", "delivered_at"], name="sharing_delivery_recipient_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("envelope", "recipient"), name="sharing_delivery_unique_recipient"),
                    models.CheckConstraint(condition=models.Q(("accepted_at__isnull", True), ("declined_at__isnull", True), _connector="OR"), name="sharing_delivery_not_accept_and_decline"),
                ],
            },
        ),
    ]
